### ISSUE TITLE
The default provided experiment doesn't save the model it trained.

### ISSUE THREAD

**Issue by NHDaly** [openai/InfoGAN#6]
The README says:

> ## Running Experiment
> We provide the source code to run the MNIST example:
> 
> `python launchers/run_mnist_exp.py`
> 
> You can launch TensorBoard to view the generated images:
> 
> `tensorboard --logdir logs/mnist`

But running that experiment produces only a single log in `logs`, but no checkpoints in `ckt` and no logs after the model has trained. It's disappointing because I ran the experiment over a day and then it finished, and now all that work is gone.

```
root@cbe2bb86132a:/InfoGAN# find ckt
ckt
ckt/mnist
ckt/mnist/mnist_2016_08_15_03_18_12
```

```
root@cbe2bb86132a:/InfoGAN# find logs
logs
logs/mnist
logs/mnist/mnist_2016_08_15_03_18_12
logs/mnist/mnist_2016_08_15_03_18_12/events.out.tfevents.1471231106.cbe2bb86132a
```

Is there some flag setting I need to set to get useful output? If so, can that be the default? Thanks!

**Comment by NHDaly** [comment]
Also, looking at that log file, it seems to be from right when the model started, before it trained at all.

**Comment by kylemcdonald** [comment]
The default values effectively disable the checkpoints. But if you change the `snapshot_interval` for the `RegularizedGAN` from 10000 to something smaller (e.g. 100, to save once every epoch at the default `updates_per_epoch`) then you should get more checkpoints.

Also, I see a complete log history after the entire training process is done. I haven't checked the intermediate output.

**Comment by NHDaly** [comment]
Thank you, this fixed the problem! :)
